
2016-05-15 14:10:41,930 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-15 14:10:47,873 ERROR: Exception on /favicon.ico [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 19, in not_found_error
    return render_template('333.html'), 404
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 333.html
2016-05-15 14:10:53,942 ERROR: Exception on /favicon.ico [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 19, in not_found_error
    return render_template('333.html'), 404
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 333.html
2016-05-15 14:10:58,992 ERROR: Exception on /edit [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 139, in edit
    return render_template('edit.html', form=form)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: edit.html
2016-05-15 14:11:04,179 ERROR: Exception on /favicon.ico [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 19, in not_found_error
    return render_template('333.html'), 404
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 333.html
2016-05-15 14:11:52,002 ERROR: Exception on /favicon.ico [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 19, in not_found_error
    db.session.rollback()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 333.html
2016-05-15 14:11:57,250 ERROR: Exception on /favicon.ico [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 19, in not_found_error
    db.session.rollback()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 333.html
2016-05-15 14:12:02,294 ERROR: Exception on /edit [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 139, in edit
    def search():
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: edit.html
2016-05-15 14:12:07,467 ERROR: Exception on /favicon.ico [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1370, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1330, in handle_http_exception
    return handler(e)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 19, in not_found_error
    db.session.rollback()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 333.html
2016-05-15 14:12:49,244 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-15 14:13:21,884 ERROR: Exception on /edit [GET] [in /Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/Users/frankcorrigan/Repositories/microblog/app/views.py", line 135, in edit
    return render_template('edit.html', form=form)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/frankcorrigan/anaconda3/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: edit.html
2016-05-15 14:27:54,112 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-15 14:33:24,896 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-15 14:36:41,092 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-15 14:36:41,658 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-17 06:12:10,087 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-17 06:12:10,746 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
2016-05-17 06:14:06,780 INFO: microblog startup [in /Users/frankcorrigan/Repositories/microblog/app/__init__.py:50]
